### Get All Users
GET http://localhost:3000/users
Accept: application/json


### Get User by ID
GET http://localhost:3000/users/68464be184c18c35ddaace29
Accept: application/json


### Create a New User
POST http://localhost:3000/users
Content-Type: application/json

{
   "name": "Johnny Paul",
   "phone": "636-5652",
   "email": "johny@example.com",
   "password": "securepass"
}


### Update User by ID 
PUT http://localhost:3000/users/684713b4f9e3d90475fb9684
Content-Type: application/json

{
   "name": "Johnny Paul",
   "phone": "636-5652",
   "email": "updated@example.com",
   "password": "newsecurepass"
}


### Delete User by ID 
DELETE http://localhost:3000/users/
Accept: application/json
