### Get All Users
GET http://localhost:10000/users
Accept: application/json


### Get User by ID
GET http://localhost:10000/users/68464be184c18c35ddaace29
Accept: application/json


### Create a New User
POST http://localhost:10000/users
Content-Type: application/json

{
   "name": "Johnny Paul",
   "phone": "542-3142",
   "email": "johnypa@example.com",
   "password": "securepass"
}


### Update User by ID 
PUT http://localhost:10000/users/68478e5e7154fb88d2ddea54
Content-Type: application/json

{
   "name": "Johnny Paul",
   "phone": "636-5652",
   "email": "updated@example.com",
   "password": "newsecurepass"
}


### Delete User by ID 
DELETE http://localhost:10000/users/
Accept: application/json
